ext {
    extName = 'Animeindo'
    extClass = '.Animeindo'
    extVersionCode = 1
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:blogger-extractor"))
    implementation(project(":lib:dailymotion-extractor"))
    implementation(project(":lib:dood-extractor"))
    implementation(project(":lib:okru-extractor"))
    implementation(project(":lib:playlist-utils"))
    implementation(project(":lib:unpacker"))
}
