blank_issues_enabled: false
contact_links:
  - name: 💬 Diskusi & Tanya Jawab Komunitas
    url: https://github.com/dongnime/extensions/discussions
    about: Ajukan pertanyaan umum, saran, atau berdiskusi seputar aplikasi Aniyomi/Anikku
