ext {
    extName = 'Animexin'
    extClass = '.Animexin'
    extVersionCode = 2
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:playlist-utils"))
    implementation(project(":lib:okru-extractor"))
    implementation(project(":lib:dailymotion-extractor"))
    implementation(project(":lib:dood-extractor"))
    implementation(project(":lib:cloudflare-interceptor"))
    implementation(project(":lib:unpacker"))
}
